### ISSUE TITLE
Progression bar adds extra when past completion time

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-howlongtobeat-plugin#10]
Related to https://github.com/Lacro59/playnite-howlongtobeat-plugin/issues/7

![imagen](https://user-images.githubusercontent.com/1389286/86303241-e357df80-bbd0-11ea-83e4-ed58f0d41b58.png)

Is this intended?

**Comment by Lacro59** [comment]
Yes.
This is indict that we play more than HowLongToBeat time.

**Comment by darklinkpower** [comment]
Thanks, closing issue then.
