### ISSUE TITLE
Can not select all games and update time played to HowLongtoBeat all at once.

### ISSUE THREAD

**Issue by QubeRubix** [Lacro59/playnite-howlongtobeat-plugin#110]
When attempting to select all games and update game times via HowLongtoBeat - Set current playtime, only some games are added to the HowLongtoBeat data and alot are not.

[extensions.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/7491317/extensions.log)

**Comment by Lacro59** [comment]
By default, the plugin only sets data when a game is found.
But, you can set a match percentage to improve this:
![image](https://user-images.githubusercontent.com/124054/143777655-4af16120-9c97-4a63-9eaa-a6ef16f8dc88.png)

**Comment by QubeRubix** [comment]
Is it unable to find games from Epic? It does not seem to be able to pull
data from there and a little less than half my library can not be found.

**Comment by Lacro59** [comment]
Can you give me examples?

**Comment by QubeRubix** [comment]
Examples of games would be like For the King, Steep, Saints Row. Anything
on my Epic account is not in the How Long to Beat Data. There are also
other games not related to epic that will not show up either like ubisoft,
and some Steam Games. The data is on the Game Page sometimes but not on the
HowLong to Beat Tab.
