### ISSUE TITLE
Progressbar in fullscreen theme on gamedetails view

### ISSUE THREAD

**Issue by philipjholm** [Lacro59/playnite-howlongtobeat-plugin#111]
I am trying to get the progressbar to show up in the gamedetails view in a fullscreen theme. I've tried this but shows nothing:
<ContentControl x:Name="HowLongToBeat_PluginProgressBar" MinHeight="100" MinWidth="500" />

Is it not supported in fullscreen?

**Comment by Lacro59** [comment]
fixed for the next release

**Comment by philipjholm** [comment]
@Lacro59 
Is there any tutorial for implementing it in a full screen theme? Whatever I do it doesn't show :(
