### ISSUE TITLE
Change description of chart 

### ISSUE THREAD

**Issue by Andei** [Lacro59/playnite-howlongtobeat-plugin#112]
I would change the text into something like "Games in HLTB database", because that's what it is and not the completed games. Here 28 completed but 39 in db.

![XfwL2LLM8J](https://user-images.githubusercontent.com/7351090/142841075-56de84f8-aaff-4fb6-9d42-bec3fd0bed29.png)

**Comment by Lacro59** [comment]
This screen is in the HowLongToBeat data. Therefore, the data comes from HowLongToBeat.
Isn't that explicit enough?

**Comment by Andei** [comment]
It‘s not about HltB, it’s about the word completed - that#s wrong
