### ISSUE TITLE
Ability to change the header of the extension for the localization in Italian to "Tempo di gioco"

### ISSUE THREAD

**Issue by LuKa8989** [Lacro59/playnite-howlongtobeat-plugin#114]
Ability to change the header of the extension for the localization in Italian to "Tempo di gioco"

**Comment by Lacro59** [comment]
I added a new localization (`LOCCommonGameTime`) usable in theme: [here](https://github.com/darklinkpower/Harmony/blob/1638b85a15f69410993cd28e87dc88bb1a8c3bca/source/Views/DetailsViewGameOverview.xaml#L271)
You must remplace `<Label Content="HowLongToBeat" />` by `<Label Content="{DynamicResource LOCCommonGameTime}" />`
