### ISSUE TITLE
Duplication of entries in HLTB website when setting playtime

### ISSUE THREAD

**Issue by JoelRoxx** [Lacro59/playnite-howlongtobeat-plugin#116]
When a game has been closed and the option is set to automatically upload the playtime to user's HLTB account, instead of updating the already pre-existing entry, a new entry is created of the same game with the updated playtime, leading to several duplicate entries on the site.

Not all games are affected all the time, but unsure how to replicate the issue. Could be because the game entry was already created outside the extension's help.

**Comment by Lacro59** [comment]
Try to delete duplicate data in HowLongToBeat.
After, you must refresh your user data in Plugin.
And try again.

**Comment by JoelRoxx** [comment]
So what I did is, deleted all entries from HowLongToBeat of the affected game and then refresh data in playnite. But the problem still persists. Then I clear data from HLTB addon just to see if that helps, but still no luck, duplicates still exists.
