### ISSUE TITLE
Progress bar in game description

### ISSUE THREAD

**Issue by Luneyes** [Lacro59/playnite-howlongtobeat-plugin#118]
Since the latest version, the progress bar doesn't show anymore in the game description.

Is it a bug or is it a restriction from Playnite latest version?
Any way to make it show again when you click on a game instead of the group view?

**Comment by Lacro59** [comment]
Do you have recently migrate to Playnite 9?

**Comment by Luneyes** [comment]
Yes, I just migrated to Playnite 9.11 today and HLTB is 2.5.2.

**Comment by Lacro59** [comment]
OK.
With Playnite 9, the plugin integration must be do with a custom theme.
If you used the default theme, there is DefaultExtend theme.

**Comment by Luneyes** [comment]
Oh I see!
Thank you very much, this theme looks promising!
