### ISSUE TITLE
[Enhancement] Skip completed entries for submitting playtime

### ISSUE THREAD

**Issue by Andei** [Lacro59/playnite-howlongtobeat-plugin#124]
For setting your current playtime choose the playing entry and skip the completed ones.

E.G. on a second run it always takes the first entry even when it's completed
![grafik](https://user-images.githubusercontent.com/7351090/147826978-3046addb-c650-4280-8fe3-adcd99b53c5d.png)

**Comment by Lacro59** [comment]
The plugin set the state "Playing" when you define your current time.
This is the case after a game session, but I can disable this for a manual set.

**Comment by Andei** [comment]
It' not about setting "Playing", it's about choosing always the oldest existing entry on the HltB website and overwriting it.

A check would be nice, something like --> more than one entry --> existing "Playing" one --> take this one
