### ISSUE TITLE
Game progress bar is located at the end of the bar when there's no "Main Store+Extas" and "Completionist"

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-howlongtobeat-plugin#13]
Game progress bar is located at the end of the bar when there's no "Main Store+Extas" and completionists, even when time is still lower than the completion time

![Playnite DesktopApp_9uYx0nyxZb](https://user-images.githubusercontent.com/1389286/86808307-5681ab80-c040-11ea-805f-cbaf0f7104fd.png)

**Comment by Lacro59** [comment]
This problem is allreay resolve with the next version (not published).
