### ISSUE TITLE
Game Selection List Appears Several Times After Latest Update

### ISSUE THREAD

**Issue by burnpsy** [Lacro59/playnite-howlongtobeat-plugin#135]
As of the latest update, this add-on frequently opens the game selection list for HLTB when there's no game on that site set. I tried to play MTG Arena (which I intentionally did not setup with this add-on) and the game selection list opened twice before the game would load, followed by another time after the game closes. For clarity, I mean this window appears when I hit Play: 
![image](https://user-images.githubusercontent.com/6007819/149869988-cbe58c55-7bf2-45c6-b910-46302487e22e.png)

I note that this is despite the option to display the game selection list being deselected in the settings for this add-on:
![image](https://user-images.githubusercontent.com/6007819/149869761-9650c19a-4f82-492d-9648-f13db5b54649.png)

This seems somewhat aggressive and likely in error?

EDIT: After posting this report, this add-on proceeded to show the game selection list for basically every single game in my library that was not already set-up with this add-on. I think something went wrong in the update?

**Comment by Lacro59** [comment]
will be fixed with next release.
