### ISSUE TITLE
Add options to only show specific games

### ISSUE THREAD

**Issue by ATNewHope** [Lacro59/playnite-howlongtobeat-plugin#138]
1. filtered games (in HLTB tab)
2. Not hidden games (in HLTB settings)

**Comment by Lacro59** [comment]
I don't understand what you want.

**Comment by iNgeon** [comment]
Loving the plugin.

- Would really appreciate having an added column to tick of games completed and when enabling filters have the completed games or dedicated multiplayer games hidden.

- Also would like an option to have the plugin have presets for displaying games in a typical sort order, like always sort by Time played or Time to Beat. 

Really been using the plugin to actually start finishing games and depending on the mood aim for long play times or shorter play times to complete.

- Also side note, dont know if Howlongtobeat has an API, would be awesome to tie this into each other

https://howlongtobeat.com/user?n=Username&s=games&completed=1
