### ISSUE TITLE
Change the tags from "1" to "01" and "5" to "05"

### ISSUE THREAD

**Issue by JunoArc** [Lacro59/playnite-howlongtobeat-plugin#145]
The HLTB tags 1 to 5 hours and 5 to 10 hours should be changed to include a "0" before the first number to be able to list them in order. As you can see I created my own tags and it lists them in good order but normally the tag 5 to 10 hours is between the tag 40 to 50 and the tag 50 to 60.

[picture](https://playnite.link/forum/attachment.php?thumbnail=2197)

**Comment by Lacro59** [comment]
With the last release, try to remove all hltb tag:
![image](https://user-images.githubusercontent.com/124054/169811184-b97a74bf-e7a2-4ac6-acfb-b832af9a62aa.png)

And set tag for all games:
![image](https://user-images.githubusercontent.com/124054/169811328-83248b54-1f00-41a9-b25a-1063920d627f.png)
