### ISSUE TITLE
Playnite v9.16 crash

### ISSUE THREAD

**Issue by iNgeon** [Lacro59/playnite-howlongtobeat-plugin#147]
Trying to use Howlongtobeat in playnite results in the extension crashing

[extensions.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/8188051/extensions.log)
[playnite.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/8188052/playnite.log)

**Comment by Lacro59** [comment]
Can you try with the v2.10.1?
