### ISSUE TITLE
Crash when using extension sidebar item

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-howlongtobeat-plugin#148]
Probably the same as #147?

[hltb_log.zip](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/8189486/hltb_log.zip)

![image](https://user-images.githubusercontent.com/1389286/156860450-34266c2c-64ae-420c-848e-f86bbcf0009c.png)

**Comment by Lacro59** [comment]
Can you try with the v2.10.1?

**Comment by darklinkpower** [comment]
Confirmed it's fixed.
