### ISSUE TITLE
No results being returned on searching

### ISSUE THREAD

**Issue by Jhanlon95** [Lacro59/playnite-howlongtobeat-plugin#152]
When trying to apply HowLongToBeat times in Playnite nothing is being found when searching for games. This appears to be happening on all games

![image](https://user-images.githubusercontent.com/11045596/169499326-f20f0378-a69f-4c7e-88b4-a58cd4eef79b.png)

Checking the extensions.log I am seeing this being returned:

> 20-05 10:29:17.699|ERROR|HowLongToBeat#Web:Web error with status code NotFound
20-05 10:29:22.567|ERROR|HowLongToBeat#Web:Web error with status code NotFound
20-05 10:29:23.996|ERROR|HowLongToBeat#Web:Web error with status code NotFound
20-05 10:31:18.899|ERROR|HowLongToBeat#Web:Web error with status code NotFound

**Comment by KiimaRo** [comment]
This seems to be happening for a lot of people. Me included.

**Comment by rottenredfish** [comment]
+1 ; been like this for a day or so now.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/d5deed6154f79dda41df86bc240161ba322fe9ed
