### ISSUE TITLE
Syncing user data: "Specified argument was out of the range of valid values. Parameter name: index."

### ISSUE THREAD

**Issue by Thexder0** [Lacro59/playnite-howlongtobeat-plugin#154]
First, thank you so much for this plugin, it is awesome, your work is really appreciated! Thank you!

Now to the issue: I am a new Playnite user, just installed this plugin last week. When I press the "Authenticate" button inside the HowLongToBeat plugin in Playnite, I get a browser window with the "Member Login" page in HLTB; I enter my HLTB login and password, and everything seems to work -- the browser window changes as if I logged into HLTB, showing my username and avatar picture from there, the plugin shows "User is authenticated", and right after I get the "HowLongToBeat - Syncing user data" progress bar (going left and right), so it seems the plugin is downloading my data from HLTB just fine.

However, after a long time (15 to 20 minutes), the progress bar vanishes and I get the error notification mentioned above on Playnite's left sidebar: "Specified argument was out of the range of valid values. Parameter name: index.". I see no personal user data from HLTB imported (I suppose it would show completion dates and some other data, but none can be found), so I gather no user data was imported after all.

More info: Playnite 9.0; HLTB Plugin 2.10.2; Windows 10 64-bit. I do have a huge amount of entries in HLTB (1.4K completions + 1.7K in Backlog), if this is relevant somehow?

Let me know what other useful data I can provide... Maybe the Extensions.log can be helpful? Well, here it goes. :D

Cheers!

[extensions.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/8820863/extensions.log)

**Comment by Lacro59** [comment]
fixed with last release
