### ISSUE TITLE
I think that there is a wrong submodule link

### ISSUE THREAD

**Issue by BanCrash** [Lacro59/playnite-howlongtobeat-plugin#165]
Since #157 .gitmodules now references @Jhanlon95 repository instead yours @Lacro59 . I think this is a mistake so I open this issue to letting you know in case I'm right:

https://github.com/Lacro59/playnite-howlongtobeat-plugin/blob/635513c1067ddaabd961ef60fc5bd7e24dd1df04/.gitmodules#L3

**Comment by Lacro59** [comment]
fixed
thanks
