### ISSUE TITLE
"Current Playnite version is not supported" on Playnite 10.2

### ISSUE THREAD

**Issue by Zombikaze** [Lacro59/playnite-howlongtobeat-plugin#167]
On Playnite 10.2 and was having issues with the add-on (first it was blank search results, then to fail authentication, then failed to launch when Playnite was started), so when v3.0 released I updated as soon as possible. Now when I start Playnite it says the add-on can't load because my Playnite version is not supported.

**Comment by Lacro59** [comment]
You must update Playnite to 10.3
