### ISSUE TITLE
Can't sync data for Age of Empires 4

### ISSUE THREAD

**Issue by Kinc4id** [Lacro59/playnite-howlongtobeat-plugin#168]
When I try to sync AoE4 with How Long To Beat I get this error:

HowLongToBeat
Age of Empires IV
Platform not approved.

**Comment by Lacro59** [comment]
Did you defined thé platform in plugin settings?

**Comment by Kinc4id** [comment]
In the game details? Everything is filled automatically and the platform is set to PC (Windows).

I get the same error with The Cycle.

**Comment by Lacro59** [comment]
This option is not set automatically, you must set it:
![image](https://user-images.githubusercontent.com/124054/196035809-16d88403-f830-4cc6-8e89-78bccef10f3f.png)

**Comment by Kinc4id** [comment]
Ah, I see. That fixed it. Thanks.
