### ISSUE TITLE
Platform unsupported

### ISSUE THREAD

**Issue by keatit71** [Lacro59/playnite-howlongtobeat-plugin#169]
Plugin keeps giving me platform unsupported messages with windows games i have installed like gta 5, is it possible to disable this notification as it is annoying.

**Comment by Lacro59** [comment]
Can you give the exact error message and log file?

**Comment by keatit71** [comment]
Its taken you so long to respond to this issue either the issues been fixed or i'm just not getting it anymore.

**Comment by czornikk** [comment]
I'm also getting this error with, for example, Overwatch. Notification looks like follows:

![image](https://user-images.githubusercontent.com/47973790/208310811-990afc0a-344f-4e74-987b-15d4a6d5f02c.png)

Let me know if you need more information and how I can provide it too you.

**Comment by Terael76** [comment]
anyone had an idea how to fix this Problem?
