### ISSUE TITLE
Broken not import the game into HLTB

### ISSUE THREAD

**Issue by Felzow47** [Lacro59/playnite-howlongtobeat-plugin#175]
![image](https://user-images.githubusercontent.com/49567056/205173476-c6df9437-d0aa-4894-8fc5-32fff6886d75.png)

**Comment by Lacro59** [comment]
Have you defined the platforms?
![image](https://user-images.githubusercontent.com/124054/206156113-46e8eea8-dca2-41e3-bf2e-0c8d0e2aa481.png)

**Comment by Felzow47** [comment]
yes ! platform is defined

**Comment by Felzow47** [comment]
![image](https://user-images.githubusercontent.com/49567056/206462475-06d695a0-ddcd-4366-bc91-35a59bca5fcd.png)
no extension.log on my computer

**Comment by Felzow47** [comment]
here is my [extensions.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/10185938/extensions.log)

**Comment by CatCubed** [comment]
Same issue here, attaching my extensions.log as well in case it's needed

[extensions.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/10195245/extensions.log)
