### ISSUE TITLE
Unable to authenticate - "Invalid CAPTCHA" error

### ISSUE THREAD

**Issue by WingedAsarath** [Lacro59/playnite-howlongtobeat-plugin#179]
I needed to authenticate for the plugin, but the login screen that appears to authenticate through Playnite returns an "Invalid CAPTCHA" error when I try to log in.

I logged in on my Chrome browser and the HowLongToBeat site displayed a CAPTCHA I had to complete to be able to log in on Chrome. But that CAPTCHA doesn't appear in the Playnite browser to let me log in for this plugin. So at present I am unable to authenticate to use this plugin.

![image](https://user-images.githubusercontent.com/61755582/207150300-4c0fcc8d-8e09-4127-b920-4bf427b2f4c3.png)

**Comment by Lacro59** [comment]
Is the issue still present?
