### ISSUE TITLE
Authentication isn't saved though login is successful

### ISSUE THREAD

**Issue by Bit-fire** [Lacro59/playnite-howlongtobeat-plugin#185]
I'm in the addon-settings. Status shows "Requires authentication".
When I click on "Authenticate", the following happens:
1) A popup browser-window for "https://howlongtobeat.com/login" appears.
2) I enter my credentials and click "I am human"
3) A (really annyoing) captcha overlay appears, which I solve ("I am human" gets a green checkmark)
4) I click "login"
5) The browser-popup changes to URL "https://howlongtobeat.com/user/MyUserName" and shows my profile
6) I can browse my profile or do whatever, the popup does not close automatically
7) Once I close the browser I get back to the Addon's settings, status is still "Requires authentication"

Expected: After login, the browser-window should close and status should change to "authenticated".
Alternatively, after login and manually closing the browser-window status should change to "authenticated".

System: Windows 10
Addon-Version: 2.10.2
Playnite Version: 9.19 (same behaviour with 9.18)

**Comment by Lacro59** [comment]
I no longer maintain the 2.x branch for Playnite 9.

**Comment by Bit-fire** [comment]
Issue is resolved, problem doesn't occur anymore since some time. Sorry, I forgot about this ticket.
