### ISSUE TITLE
Plugin Changing Storefront on Website

### ISSUE THREAD

**Issue by GCTuba** [Lacro59/playnite-howlongtobeat-plugin#191]
I have the option turned on to automatically update my playtime from Playnite into the howlongtobeat.com website. This works great, but I noticed a bug where it removes the storefront you have the game under on the website when you do it. For example, I have Avadon 2 listed under the Humble Bundle storefront and it is in both my Playing and Backlog lists. However, when the plugin updates my time played from my latest play session, it reverts Avadon 2 to the default storefront which is just "(Select Storefront)". This should be fixed so the plugin only updates the time played and not touch the storefront field.

**Comment by f1eryone** [comment]
Similar, but seems to be changing some but not all games I update or add to Bethesda.

**Comment by Lacro59** [comment]
Is this resolved with the latest version?

**Comment by GCTuba** [comment]
It works if the storefront shows up on the new Storefront menu but unfortunately, I have several games that aren't on the list. They continue to default to "(Select Storefront)" on game exit. Direct download and Microsoft Store currently, but there could be others. Either they need to be added to the list somehow or (preferably) the extension should stop touching the storefront field.

**Comment by Lacro59** [comment]
can you give examples?

**Comment by GCTuba** [comment]
I don't have any Microsoft Store games downloaded but I'm playing a game called Vampires Dawn right now. It's not on a storefront, I downloaded it directly from the developer's website so I have the storefront listed as "Direct Download" in my backlog. When I play the game and exit out, the time updates on HLTB correctly but the storefront changes back to "(Select Storefront)". This will also be a problem when I start playing emulated games because I have them categorized as Direct Download as well. It would be very nice if we could just disable updating the storefront altogether in the extension settings.
