### ISSUE TITLE
Playnite is crashing when Turkish Language selected

### ISSUE THREAD

**Issue by qoray99** [Lacro59/playnite-howlongtobeat-plugin#199]
I installed the HowLongToBeat add-on to Playnite, but the add-on causes the program to crash when Playnite is in Turkish. I can disable the plugin and use Turkish or I can use Playnite in English and use the plugin. There is a language problem with the plugin. How can I solve this situation? I want the plugin not to cause problems when using Playnite in Turkish.

**Comment by qoray99** [comment]
I think the problem is with the Daze theme. I didn't have such a problem with the Mythic theme. When I delete the files of the Mytic theme, the same thing happens again. So I left the Mytic theme installed and selected the Daze theme. I think the problem is solved. Playnite doesn't crash, strange solution :D

**Comment by Lacro59** [comment]
Can you post your playnite.log & extention.log?

**Comment by qoray99** [comment]
> Can you post your playnite.log & extensions.log?

I deleted add-on. I'm using Playnite without HLTB add-on with Mythic Theme. This theme too was crashing with HLTB add-on when Turkish language. I think this problem is for every theme.

**Comment by Lacro59** [comment]
Can you try with the last release?
