### ISSUE TITLE
v3.2.0 - Crash when user is Authenticated

### ISSUE THREAD

**Issue by zeroantix** [Lacro59/playnite-howlongtobeat-plugin#200]
Hi Lacro59,

I've seen couple of comments on Reddit about the latest HLTB (v3.2.0) extension causing a crash. 

**See:** https://www.reddit.com/r/playnite/comments/194e37j/updated_how_long_to_beat_causes_startup_failure/?utm_source=share&utm_medium=web2x&context=3

I had the update installed and didn't experience any crash. This got me thinking, why crash some users, and not others? I then noticed that I was not authenticated within the plugin. I updated my credentials and it displayed User Authenticated - and this is when I experienced my first crash. It wasn't instantly, it was when I entered Fullscreen Mode to a theme that has HLTB integration. What adds confusion is that once crashed, Playnite fails to re-open, or if it does, it crashes within a few seconds. No error message. The only way to get Playnite to re-open and stay open is run in Safe Mode (via argument in my case).

I uninstalled HLTB and was able to open Playnite as normal. Rolling back to the previous version of HLTB was fine, the plugin didn't cause a crash, authenticated or not.

Apologies it's not much to go off, but until authenticated in the latest release there were zero crashes.

Hope this info helps if other users are experience.

Zero

**Comment by philipjholm** [comment]
Not a very helpful comment from me maybe, but I have exactly the same problem.

**Comment by Lacro59** [comment]
Can you post your playnite.log & extention.log?

**Comment by philipjholm** [comment]
> Can you post your playnite.log & extensions.log?

Sure, here they are. Thanks for looking into this!
[extensions.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/13931231/extensions.log)
[playnite.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/13931232/playnite.log)

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-howlongtobeat-plugin_3_2_0.zip](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/13981556/playnite-howlongtobeat-plugin_3_2_0.zip)

**Comment by zeroantix** [comment]
Hi Lacro59

With the above .zip alternative, I was able to switch between Desktop and Fullscreen several times. It even diplayed the HLTB data within the Theme(s). I was authenticated during this process. I refreshed the HLTB Data of a a couple of games, switched mode from Desktop to Fullscreen and the application crashed to Windows.

I checked the extension.log after this first crash and was able to see the following:

19-01 06:10:53.818|WARN |HowLongToBeat#PluginDatabaseObject`4:No HltbData for 100440
19-01 06:10:57.524|WARN |HowLongToBeat#PluginDatabaseObject`4:No HltbData for 107893

I restarted Playnite, it opened but then closed within a couple of seconds. I opened the extension log and saw:

19-01 06:11:22.552|INFO |HowLongToBeat#PluginDatabaseObject`4:LoadDatabase with 607 items - 00:01.78
19-01 06:11:22.887|WARN |HowLongToBeat#PluginDatabaseObject`4:No HltbData for 107893

Restarted Playnite multiple times again (each time resulting in a crash to Windows), but the extension.log didn't record any warnings. Example:

19-01 06:29:04.071|INFO |HowLongToBeat#PluginDatabaseObject`4:LoadDatabase with 607 items - 00:01.74

Maybe the authetication status irrelevant,  maybe it's rather any sort of change/update to the data?

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by philipjholm** [comment]
> Can you try with the last release?

You are the best! This seemed to have fixed the problem.

**Comment by philipjholm** [comment]
I am afraid it just crashed for me as well :/ It's weird because it takes some time before it happens so it worked starting and restarting two times for me before it happened for me.

**Comment by Verssgn** [comment]
I have the same issue, also crashes on fullscreen mode.

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by ld892012** [comment]
For the moment it seems to work for me ^^

**Comment by ld892012** [comment]
2 months after I still have no issues, maybe this issue can be closed now because as it seems to be resolved
