### ISSUE TITLE
Crashing with the Helium Theme

### ISSUE THREAD

**Issue by greensad** [Lacro59/playnite-howlongtobeat-plugin#203]
Having some trouble with HLTB crashing playnite at startup while using the helium theme. This may also be a result of integration of the Helium theme, other mods, & HLTB concurrently running. In any case playnight crashes and disabling HLTB solves the issue. I should also mention that this crash only happens maybe 90% of the time and upon recovering from a crash when playnite asks if I want to disable add-ons, select no rarely results in a crash from my testing which is of course about as non-conclusive as it sounds lmao, I only did a few dozen launches. Anyway log is included, lmk if I can help in any way!

[playnite.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/14074658/playnite.log)

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by greensad** [comment]
> Can you try with the last release?

unfortunately still crashing

**Comment by Lacro59** [comment]
Can you try with the last release?

**Comment by greensad** [comment]
Appears to be solved, nice work!
