### ISSUE TITLE
Thumbnails No Longer Showing Up When New Games Added to Library

### ISSUE THREAD

**Issue by GCTuba** [Lacro59/playnite-howlongtobeat-plugin#206]
When the extension scans the library, detects a new game, and opens a popup for you to select which game it is from a list, the thumbnails no longer show up. It still shows information like game title, platforms, and time to beat, but the thumbnails no longer load. This makes it more difficult to select the correct game, especially if there are two with the same name. This has been happening for several weeks now.

**Comment by KiimaRo** [comment]
Same issue still.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/97f3d3901a4c9d84009d47f5ddbe4a5a00b20f91

**Comment by GCTuba** [comment]
So does this mean an update is coming? Because the same thing happened just now.

**Comment by KiimaRo** [comment]
Wondering this too, been 2 weeks since the closing of the ticket and still not working.

**Comment by GCTuba** [comment]
You forgot to push the update. This problem is still happening.

**Comment by GCTuba** [comment]
This issue has still not been resolved. I see that you made some changes to the code a month ago but the last update to the extension was February 4th.
