### ISSUE TITLE
Missing localizations in options menu

### ISSUE THREAD

**Issue by wilco375** [Lacro59/playnite-howlongtobeat-plugin#209]
There seem to be several options in the HLTB extensions menu of which the localization is missing:
![image](https://github.com/Lacro59/playnite-howlongtobeat-plugin/assets/7385023/a936c649-b8db-4028-88fe-121ff28b9aee)
Looking at the source code, these localizations are indeed only referenced in https://github.com/Lacro59/playnite-howlongtobeat-plugin/blob/master/source/HowLongToBeat.cs, and not in any of the localization files.

Edit: there are several other places where the localization is missing too.

**Comment by Lacro59** [comment]
Do you still have this issue?
