### ISSUE TITLE
[Feature Request] Update HLTB List from Playnite Completion Status

### ISSUE THREAD

**Issue by matthewdias** [Lacro59/playnite-howlongtobeat-plugin#210]
It would be nice to sync to HLTB lists when you change completion status in Playnite. Playnite lets you select only one status, while HLTB lets you select multiple, so probably only a 1-way sync Playnite -> HLTB is feasible. If we could manually map between the two lists of statuses, similar to the existing storefront configuration, that would be even nicer (Including custom tabs).

Playnite:
![image](https://github.com/Lacro59/playnite-howlongtobeat-plugin/assets/3302524/882ac62b-4f47-41fc-bdc3-9dcdc4ca9baa)

HLTB:
![image](https://github.com/Lacro59/playnite-howlongtobeat-plugin/assets/3302524/a0bc58f5-c371-4de6-98a0-d5f38ed8ce48)

**Comment by Lacro59** [comment]
with last release
