### ISSUE TITLE
HLTB account data not updating

### ISSUE THREAD

**Issue by ACMClassicalCode** [Lacro59/playnite-howlongtobeat-plugin#211]
I have auto update HLTB account data turned on. I have confirmation message after quitting a game turned on. Whenever I confirm to update data nothing changes on the HLTB website. I am authenticated in the plugin menu with my HLTB account.

**Comment by Lacro59** [comment]
Can you post your extension.log?

**Comment by ACMClassicalCode** [comment]
Apologies it seems to be working now. Thank you for the great extension!

**Comment by ZOMGsheikh** [comment]
[extensions.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/15444803/extensions.log)

I too have similar issue. Recently I was playing a GOG version of a game, the extension properly added to HLTB website my playtime . But now whichever game I m playing, it does not get updated on HLTB website. My last few lines from log is me starting Alan Wake, which I played first for few minutes but nothing in HLTB even after confirmation message. Then even right clicked the game in playnite and set my current playtime under HLTB extension and still no update on website.

**Comment by Lacro59** [comment]
Can you try this?
[playnite-howlongtobeat-plugin_3_3.zip](https://github.com/user-attachments/files/16470777/playnite-howlongtobeat-plugin_3_3.zip)

**Comment by hlebushekhub** [comment]
> Can you try this? [playnite-howlongtobeat-plugin_3_3.zip](https://github.com/user-attachments/files/16470777/playnite-howlongtobeat-plugin_3_3.zip)

this version fixed the issue for me!
