### ISSUE TITLE
The "Loading..." progress bar does not disappear 

### ISSUE THREAD

**Issue by vidz97** [Lacro59/playnite-howlongtobeat-plugin#213]
When I open it with the button on the sidebar, the "Loading..." progress bar keeps showing even though the content has loaded.

**Comment by k0te1k4** [comment]
Same problem

**Comment by Lacro59** [comment]
Can you post your extension.log?

**Comment by mrzhu666** [comment]
also, Same problem

**Comment by mrzhu666** [comment]
[extensions.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/15321491/extensions.log)

**Comment by FrostByte404** [comment]
I'm having the same issue

**Comment by Lacro59** [comment]
Can you try this version?
[playnite-howlongtobeat-plugin_3_3.zip](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/15416105/playnite-howlongtobeat-plugin_3_3.zip)

**Comment by cjhart20** [comment]
Same here

**Comment by Swansocl1** [comment]
Same issue here

**Comment by Lacro59** [comment]
Can you try this?
[playnite-howlongtobeat-plugin_3_3.zip](https://github.com/user-attachments/files/16470777/playnite-howlongtobeat-plugin_3_3.zip)

**Comment by Devoxer** [comment]
Same issue for me

**Comment by Lacro59** [comment]
@Devoxer, can you post your extension.log?

**Comment by JustFameL** [comment]
Same here

**Comment by bsunter** [comment]
Same issue :(

extensions.log doesn't really provide hints

`13-08 22:05:05.163|DEBUG|SteamLibrary#SteamTagNamer:Opening C:\Users\barts\AppData\Local\Playnite\ExtensionsData\cb91dfc9-b977-43bf-8e70-55f46e410fab\tagnames-dutch.json
13-08 22:05:05.621|INFO |HowLongToBeat#HowLongToBeatDatabase:LoadDatabase with 382 items - 00:00.51
13-08 22:05:05.871|DEBUG|EpicLibrary#EpicLibrary:Found 1 installed Epic games.
13-08 22:05:07.227|DEBUG|EpicLibrary#EpicLibrary:Found 11 library Epic games.
13-08 22:05:07.228|DEBUG|SteamLibrary#SteamLibrary:Found 8 installed Steam games.
13-08 22:05:07.973|DEBUG|SteamLibrary#SteamLibrary:Found 713 library Steam games.
13-08 22:05:07.999|DEBUG|UplayLibrary#UplayLibrary:Found 0 installed Ubisoft Connect games.
13-08 22:05:08.058|DEBUG|UplayLibrary#UplayLibrary:Found 6 library Ubisoft Connect games.
`

**Comment by HelgiMagic** [comment]
same bug

**Comment by Lacro59** [comment]
Can you try this vesion?
[playnite-howlongtobeat-plugin_3_4_1.zip](https://github.com/user-attachments/files/17110307/playnite-howlongtobeat-plugin_3_4_1.zip)

**Comment by JustFameL** [comment]
> Can you try this vesion? [playnite-howlongtobeat-plugin_3_4_1.zip](https://github.com/user-attachments/files/17110307/playnite-howlongtobeat-plugin_3_4_1.zip)

It works! Thanks man 🥳🙌🏼

**Comment by Lacro59** [comment]
And now with this?
[playnite-howlongtobeat-plugin_3_4_1.zip](https://github.com/user-attachments/files/17146063/playnite-howlongtobeat-plugin_3_4_1.zip)

**Comment by JustFameL** [comment]
> And now with this? [playnite-howlongtobeat-plugin_3_4_1.zip](https://github.com/user-attachments/files/17146063/playnite-howlongtobeat-plugin_3_4_1.zip)

It's perfect now. Big thanks! Love you.
