### ISSUE TITLE
Improve Game Import

### ISSUE THREAD

**Issue by Shaarigan** [Lacro59/playnite-howlongtobeat-plugin#218]
**Problem**

When auto-importing data (e.g. on updating the game library), the extension currently isn't able to distinguish the right game when there are multiple search results, even if the search result contains an entry that is clearly identical to the game currently searched for. For every game, there will a popup dialog open, even if it could select the proper result by simply comparing the name

**Solution**

Have the extension try to distinguish the right entry when there are multiple search results found. This will limit user interaction and improve the data importet a lot.You might run all the search results through a simple function to compare the name found with the game name and if there is a clear match, choose that entry automatically

**Comment by Lacro59** [comment]
If you use this option, the plugin will get the data with the best match:
![image](https://github.com/user-attachments/assets/44d0bffd-5f13-4727-a6b1-6aa496277050)
