### ISSUE TITLE
HLTB Data Not Updating

### ISSUE THREAD

**Issue by cjhart20** [Lacro59/playnite-howlongtobeat-plugin#219]
No matter what option I try to update, I can't get all the games data to get imported. If I update all data or download all data, then go to the playnite tab, only some of my games appear. For example, if I check the "only filtered games" box, only 24 games will appear despite there being 30+ in that filter.

**Comment by Lacro59** [comment]
Data is imported if the game is found.
And there is an option to improve the search:
![image](https://github.com/user-attachments/assets/132258f3-3b09-41d1-afdc-39516b74975f)

**Comment by cjhart20** [comment]
That helped, thanks
