### ISSUE TITLE
Inflated Times Imported Compared to HLTB Website

### ISSUE THREAD

**Issue by burnpsy** [Lacro59/playnite-howlongtobeat-plugin#221]
**Describe the bug**
At some point recently, this add-on has started importing times that are completely wrong compared to the HLTB website. And not "slightly" wrong, but stuff like a game that the website says takes 52 hours for the main story gets imported as 200 hours.

**To Reproduce**
Use externsion normally. For a seemingly random selection of games, one or more of the times will be vastly inflated. I have confirmed this to be the case for Trails through Daybreak (Main reports as 200h), Eiyuden Chronicle (Main + Sides reports as 200h) and Monochrome Mobius (Main reports as 271h).

**Expected behavior**
The times would match the data on HLTB.

**Screenshots**
![In Playnite](https://github.com/user-attachments/assets/1f9f8f6f-b5d7-4bce-9dea-612ea2de9344)
![On website](https://github.com/user-attachments/assets/fab2725c-731f-4427-9ee2-546ccf5313b5)

**Extensions log**
[extensions.log](https://github.com/user-attachments/files/16436946/extensions.log)

**Comment by Taranchuk** [comment]
I have the same issue. Except it can also under report the time, for example it reports that Call of Cthulhu main story takes 21 minutes
![image](https://github.com/user-attachments/assets/b502d212-e75b-48f5-b174-e36b162aca32)
but the real time is 8 hours actually
![image](https://github.com/user-attachments/assets/997a9f87-cf9f-40b7-b47e-d618a9f03f05)

**Comment by Taranchuk** [comment]
The same thing for Control
![image](https://github.com/user-attachments/assets/226bcf18-b796-4a71-933f-48f8a4f9baa8)
![image](https://github.com/user-attachments/assets/0b70bb18-5429-40c0-9dfe-c9b52f3775da)

**Comment by Thexder0** [comment]
Just to add +1 for this odd bug, I imagine something has changed in the HLTB side, since the plugin was working beautifully a few days ago.

To add info: this happens to games that are newly added to the collection, as well as to games which had HLTB times registered inside playnite. I mean, if you "refresh" the HLTB data on old games, the new incorrect times replace the old correct ones.

**Comment by Thexder0** [comment]
Update: now, instead of crazy times,  I am getting the infamous "Vale cannot be null. Parameter name: collection" error (same one I was getting about 1 week ago). Sounds like the HLTB site is changing something, so I guess we just sit tight and wait?

**Comment by Lacro59** [comment]
Can you try this?
[playnite-howlongtobeat-plugin_3_3.zip](https://github.com/user-attachments/files/16470777/playnite-howlongtobeat-plugin_3_3.zip)

**Comment by Taranchuk** [comment]
Extracted the archive content to the plugin's folder and it works fine

**Comment by Thexder0** [comment]
> Can you try this? [playnite-howlongtobeat-plugin_3_3.zip](https://github.com/user-attachments/files/16470777/playnite-howlongtobeat-plugin_3_3.zip)

Oh, baby! Yes, this fixed all the bugs I have been seeing (both for incorrect times and "Cannont be null")! Thank you!

**Comment by burnpsy** [comment]
I can also confirm that the test version fixed it for me.

**Comment by Zer0Rem** [comment]
yes it also fixed my issue with the "Cannot be null" Thank you!
