### ISSUE TITLE
Collection: "Value cannot be null" on Game Search

### ISSUE THREAD

**Issue by SkyNinja** [Lacro59/playnite-howlongtobeat-plugin#222]
**Describe the bug**
Any time a game is searched, there are no results, and the message, "Value cannot be null. Parameter name: collection" appears in the notifications.

**To Reproduce**
1. Find a game with no HLTB info
2. Search on HLTB

In this case, the game being searched is FNaF World, which does have a listing on the site and [appears in searches](https://howlongtobeat.com/?q=FNaF%2520World) without a problem.

**Extensions log**
Apart from a single message about my local database being loaded, these errors are the only messages in extensions.log about HLTB.

```01-08 22:12:05.884|ERROR|HowLongToBeat#Common:Error on <SearchData>b__0()|C:\Projects\C#\Lacro59\playnite-howlongtobeat-plugin\source\Views\HowLongToBeatSelect.xaml.cs|0
System.ArgumentNullException: Value cannot be null.
Parameter name: collection
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at HowLongToBeat.Services.HowLongToBeatClient.<SearchTwoMethod>d__47.MoveNext() in C:\Projects\C#\Lacro59\playnite-howlongtobeat-plugin\source\Services\HowLongToBeatClient.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HowLongToBeat.Views.HowLongToBeatSelect.<>c__DisplayClass15_0.<SearchData>b__0() in C:\Projects\C#\Lacro59\playnite-howlongtobeat-plugin\source\Views\HowLongToBeatSelect.xaml.cs:line 0```

**Comment by GCTuba** [comment]
Started having this issue as well whenever a new game is added to my library. Currently not populating times for Jusant, Starfield, and Still Wakes the Deep.

**Comment by darklinkpower** [comment]
As a suggestion, a safety practice that also fixes this issue, it's generally recommended to return an empty List/IEnumerable rather than null in methods that have those return types:

https://github.com/Lacro59/playnite-howlongtobeat-plugin/blob/68e72d1039f09975fd0b200e91e2a64127dc1e71/source/Services/HowLongToBeatClient.cs#L101-L134

The benefits include not having to have safe guards and null checks in the caller method, preventing runtime errors when performing iterations, linq and other methods over the collection.

Here's a small video about this topic: https://www.youtube.com/shorts/G82njnbeqVA

**Comment by SkyNinja** [comment]
That would fix the immediate error message, but wouldn't the underlying failure to contact the API just go more easily unnoticed then?

**Comment by Lacro59** [comment]
Can you try this?
[playnite-howlongtobeat-plugin_3_3.zip](https://github.com/user-attachments/files/16470777/playnite-howlongtobeat-plugin_3_3.zip)

**Comment by Sergiokool** [comment]
> Can you try this? [playnite-howlongtobeat-plugin_3_3.zip](https://github.com/user-attachments/files/16470777/playnite-howlongtobeat-plugin_3_3.zip)

It works now thanks Lacro :D You can update on playnite the fix to help the rest of the people , cheers 👯

**Comment by Nazband** [comment]
Tried your link Lacro, it work! Think you can push it to update on playnite.

**Comment by Mowlawner** [comment]
chiming in to confirm the link you posted is working for me!

**Comment by SkyNinja** [comment]
Ditto, that change seems to have fixed it. Tested with a few games I added within the last couple days, and was able to grab the info for every one of them that has info. Gonna go ahead and close this, then.
![2024-08-02_16-10-07-511](https://github.com/user-attachments/assets/3f79b6ef-2461-4434-884f-36a25f6280c9)

**Comment by Dobbelklick** [comment]
Using 3.3 and this error is still happening.
