### ISSUE TITLE
HowLongToBeat Value cannot be null. Parameter name: collection

### ISSUE THREAD

**Issue by JobiMorkos** [Lacro59/playnite-howlongtobeat-plugin#223]
**Describe the bug**
I can't download nor search on howlongtobeat games meaning I have no time showing on my hltb

**To Reproduce**
Trying to have a metadata of howlongtobeat time games, Search won't show a single game and even changing platforms or adding an account on the settings still doesn't work

**Expected behavior**
I don't have a htlg metadata games

**Screenshots**
![Screenshot (3)](https://github.com/user-attachments/assets/375685a1-6f08-4629-97a6-66079a20d985)
![Screenshot (2)](https://github.com/user-attachments/assets/8b6410de-22aa-470f-988e-58c3d323b19c)
shows up if I'm trying to download hltb metadata
![Screenshot (5)](https://github.com/user-attachments/assets/53d1da78-9aa2-415e-affb-5f46ef378a4b)

**Extensions log**
[HowLongToBeat_2024-08-03.zip](https://github.com/user-attachments/files/16477957/HowLongToBeat_2024-08-03.zip)

**Comment by Lyncon6EchO** [comment]
It's been happening to me since yesterday too

**Comment by BloodShed-Oni** [comment]
Also happens when using "Download Plugin data..." from the extension menu

**Comment by Lacro59** [comment]
#222
