### ISSUE TITLE
Plugin problems with games that don't have any data yet (tested in v3.4)

### ISSUE THREAD

**Issue by eHanus** [Lacro59/playnite-howlongtobeat-plugin#225]
A game that has no playtime values in the HLTB database will be imported by the plugin but this will result in the plugin displaying a generic data screen and throwing an error on trying to refresh or delete the data.

![image](https://github.com/user-attachments/assets/2ee82461-0ec1-43d2-946e-039af206ef3f)
 This can be worked around by selecting multiple games (one of them seems to have to be unaffected by this) and deleting their data from the context menu. Then one can just avoid loading new data from HLTB or reload the empty data set which will re-create the issue.

**To Reproduce**
Take any game with an HLTB entry and no time information. If this is added one can open the entry and see the same details as in the screenshot.

Trying to refresh or delete the entry by itself will throw this error.
![image](https://github.com/user-attachments/assets/6857986b-3f99-4ad4-aa2f-0faaae7be98d)

**Comment by Thexder0** [comment]
+1; got that too from the newest version of the plugin in the game "Telepath Tactics Liberated"; it DOES have a HLTB page, but with no times, and I get the exactly same bug, Yes, not even the "delete data" button works, as you said.
