### ISSUE TITLE
StartPage widget dont work

### ISSUE THREAD

**Issue by CinnamonShaey** [Lacro59/playnite-howlongtobeat-plugin#228]
As title says i cant get the widget chart to show anything, i have authenticated and everything, tried to refresh data but nothing i have tried to do makes it work

![image_2024-08-11_181420695](https://github.com/user-attachments/assets/e51b33b1-ee43-4a21-a475-49ff043f5212)

**Comment by Lacro59** [comment]
Do you have data in the plugin user view?
Any errors?
