### ISSUE TITLE
Add option to show time to beat game instead of progress bar

### ISSUE THREAD

**Issue by BargainSale** [Lacro59/playnite-howlongtobeat-plugin#230]
Is it possible to add an option to show only the time to beat the game (number) instead of a progress bar?

I think this would make the info less cluttered and more customizable. Having the option to set the plugin to show either main story or completionist and round the minutes up or down for an even cleaner look would be a great improvement too.

Something similar to the tag system would be sufficient if it's a lot to implement, but showing the number of hours in place of the bar.

**Comment by Lacro59** [comment]
The elements displayed in the theme depend on the modder.
https://github.com/Lacro59/playnite-howlongtobeat-plugin/wiki/Addition-in-a-custom-theme
