### ISSUE TITLE
Selection window cutting off the content at the bottom in some themes

### ISSUE THREAD

**Issue by fernandoepm1** [Lacro59/playnite-howlongtobeat-plugin#235]
**Describe the bug**
When trying to perform the game selection for HowLongToBeat in certains themes, the Confirm and Cancel selection buttons are clipped at the bottom
This bug is happening in NovaX, Stardust and Stardust (Legacy) and probably some other themes also.

**To Reproduce**
Clicking the HowLongToBeat button in the games detail page to open the selection window in certain themes

**Expected behavior**
The selection window should be more flexible and have adjustable size to the content to be able to view the contents at the bottom, quoting darklinkpower: "fixing it could be as easy as setting the window `SizeToContent` property" (https://github.com/darklinkpower/Stardust/issues/53#issuecomment-2412607556)

**Screenshots**
![image](https://github.com/user-attachments/assets/7924ac0b-2c1d-4549-b24c-0dcb86726ab4)

![image](https://github.com/user-attachments/assets/9b6d8e19-e3f1-4550-8ae2-d935790e77b6)

**Extensions log**
Attach Playnite's `Extensions.log` file. It is located in Playnite's installation directory in the portable version or in `%AppData%\Playnite` (Can be pasted in Explorer) in the installed version

**Comment by johnnywnb** [comment]
Potential fix proposed in PR #247
