### ISSUE TITLE
Add options "Selected games" and "Filtered Games" to bulk download

### ISSUE THREAD

**Issue by HerrKnarz** [Lacro59/playnite-howlongtobeat-plugin#238]
**Describe the solution you'd like**
At the moment, it's impossible to download HLTB data in bulk for only a specific selection of games. It would be great, if the "Download plugin data..." dialog also had the option for "Only selected games" and "Only filtered games". That would make downloading data in huge libraries a lot easier and should be very simple to implement.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-plugincommon/commit/2383411c4ff1b6bc73b78a9ffdcedf4decee405f
