### ISSUE TITLE
nothing showing up when clicking view HowLongToBeat data

### ISSUE THREAD

**Issue by Travers50** [Lacro59/playnite-howlongtobeat-plugin#240]
**Describe the bug**
When pressing view HowLongToBeat datas to add the overlay onto my dashboard, no games show up. For common games too (i.e. Payday 2, Jedi Survivor, etc.)

**To Reproduce**
Steps to reproduce the behavior: click any game, press 3 bars, hover over howlongtobeat, press view howlongtobeat datas, search, see nothing

**Expected behavior**
As done many times before, I expect to see a list of any game that could be related to whatever you searched. Like if I search Payday, i'll see crimewave edition, payday 2, payday 3 and all their data.

**Screenshots**
![Capture](https://github.com/user-attachments/assets/eab1add4-3121-4b12-829e-a4ae4d1d191c)

**Extensions log**
Attach Playnite's `Extensions.log` file. It is located in Playnite's installation directory in the portable version or in `%AppData%\Playnite` (Can be pasted in Explorer) in the installed version
[extensions.log](https://github.com/user-attachments/files/17770121/extensions.log)

**Comment by WerewolfNandah** [comment]
I'm having the same issue here. I've tried reinstalling the app, updating all of my data, no results.

**Comment by johnnywnb** [comment]
Same for me.

@Lacro59, I found the problem and a fix for it.

Changes suggested as follow:
https://github.com/Lacro59/playnite-howlongtobeat-plugin/compare/master...johnnywnb:playnite-howlongtobeat-plugin:jwnb-fix-240

I'm happy to submit a PR if it helps. Let me know.

**Comment by Llama23** [comment]
any fix ? only just got playnite and this aint workin

**Comment by Beats24-7** [comment]
> Same for me.
> 
> @Lacro59, I found the problem and a fix for it.
> 
> Changes suggested as follow: [master...johnnywnb:playnite-howlongtobeat-plugin:jwnb-fix-240](https://github.com/Lacro59/playnite-howlongtobeat-plugin/compare/master...johnnywnb:playnite-howlongtobeat-plugin:jwnb-fix-240)
> 
> I'm happy to submit a PR if it helps. Let me know.

This cannot be fixed locally as there is no such file within the playnite folder, correct?

**Comment by Sergiokool** [comment]
> Same for me.
> 
> @Lacro59, I found the problem and a fix for it.
> 
> Changes suggested as follow: [master...johnnywnb:playnite-howlongtobeat-plugin:jwnb-fix-240](https://github.com/Lacro59/playnite-howlongtobeat-plugin/compare/master...johnnywnb:playnite-howlongtobeat-plugin:jwnb-fix-240)
> 
> I'm happy to submit a PR if it helps. Let me know.

share the fixed plugin please since Lacro seams to be away and miss in action :(

**Comment by johnnywnb** [comment]
I've made a hotfix release while Lacro is away. You can find it there:

https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.5.1-hotfix

To install it, download the .pext file and double-click on it while Playnite is open. It should suggest you to install it.

**Comment by Sergiokool** [comment]
> I've made a hotfix release while Lacro is away. You can find it there:
> 
> https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.5.1-hotfix
> 
> To install it, download the .pext file and double-click on it while Playnite is open. It should suggest you to install it.

Its working again like a charm, thanks a lot mate 🥇

**Comment by Jeshibu** [comment]
@johnnywnb thanks! Making a pull request would be best way to get the fix into the main repo.

**Comment by Bovive** [comment]
> I've made a hotfix release while Lacro is away. You can find it there:
> 
> https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.5.1-hotfix
> 
> To install it, download the .pext file and double-click on it while Playnite is open. It should suggest you to install it.

Thanks, that fixed most of my games. Some games give an error however "Object reference not set to an instance of an object". The game comes up in the search, but with no associated times under it. After matching it matches with "Game test name".

![Screenshot 2024-11-16 225212](https://github.com/user-attachments/assets/176ed6cb-4757-470a-b26f-67d337c58d77)
 
Trying to delete or refresh the match gives the error.

Example games:

- Citadelum
- Rogue Waters
- United Pengium Kingdom

**Comment by Llama23** [comment]
Legend bro! ur a genius to me

**Comment by johnnywnb** [comment]
> @johnnywnb thanks! Making a pull request would be best way to get the fix into the main repo.

Done.

**Comment by eFMann** [comment]
Top man!

**Comment by WerewolfNandah** [comment]
> I've made a hotfix release while Lacro is away. You can find it there:
> 
> https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.5.1-hotfix
> 
> To install it, download the .pext file and double-click on it while Playnite is open. It should suggest you to install it.

Yes! That made it!
Thank you kindly
