### ISSUE TITLE
HLTB selection screen remains empty after clicking on the button

### ISSUE THREAD

**Issue by WerewolfNandah** [Lacro59/playnite-howlongtobeat-plugin#246]
**Describe the bug**
This bug persists after so many hotfixes posted by the creators themselves.
I'm aware this is something to do with changes applied to HLTB to their Search API parameters, but I'd like at least to leave this reported as something that keeps happening.

**To Reproduce**
Click any game, press 3 bars, hover over howlongtobeat, press view howlongtobeat datas, search, see nothing

**Expected behavior**
I expect to see a list of any games that could be related to the title of the entry you're searching for.

**Screenshots**
![HowLongToPlay Error](https://github.com/user-attachments/assets/ca77ba5c-c912-4a6c-b524-c1df49ddbca7)

**Comment by Lacro59** [comment]
#243 & https://github.com/Lacro59/playnite-howlongtobeat-plugin/commit/21d02736085e735e668885dcb4accb3b103069e7
