### ISSUE TITLE
It doesen't work (Again)

### ISSUE THREAD

**Issue by Rhaziel1** [Lacro59/playnite-howlongtobeat-plugin#253]
The search results come up empty...fo every game.
It the same problem from a couple a weeks ago

**Comment by johnnywnb** [comment]
HTLB has changed their api endpoint again. I've submitted a Pull Request for Lacro to have a look at.

In the meantime, here is a hotfix I compiled while waiting for the official release. Feel free to use it and test the fix on your side:
https://github.com/johnnywnb/playnite-howlongtobeat-plugin/releases/tag/v3.7.0-hotfix-search

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-howlongtobeat-plugin/pull/252
