### ISSUE TITLE
[Suggestion] Ability to re-define search

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-howlongtobeat-plugin#3]
Depending on the game name some games won't have results: 
![imagen](https://user-images.githubusercontent.com/1389286/84814114-9c65c980-afd6-11ea-9a60-8372700e86cb.png)

In hltb:
![imagen](https://user-images.githubusercontent.com/1389286/84814171-ae476c80-afd6-11ea-85dc-3a338416065e.png)

It would be useful to be able to redefine the search string for cases like this because otherwise, the game can't be found even if it already exists in htlb database.

**Comment by Lacro59** [comment]
do with #4
