### ISSUE TITLE
show a element if there is data and the plugin is actived crash Playnite

### ISSUE THREAD

**Issue by eminaguil** [Lacro59/playnite-howlongtobeat-plugin#40]
Hi,
When trying to use the any code from the wiki to hide elements it makes Playnite crash, for example this:
https://github.com/Lacro59/playnite-howlongtobeat-plugin/wiki/Addition-in-a-custom-theme#show-a-element-if-there-is-data-and-the-plugin-is-actived

I have using the code published previously, which works well with grids, stackpanel and others controls. The bad, it's when it's disable the custom theme integration, the element always shows without data

`<Grid Tag="{DynamicResource Ga_HasDataLog}" Visibility="{Binding RelativeSource={RelativeSource Self}, Path=Tag, Converter={StaticResource BooleanToVisibilityConverter}}">
...
</Grid>
`

**Comment by Lacro59** [comment]
I modified the wiki pages with the good informations.
Can you test it?

**Comment by eminaguil** [comment]
Tetsed, Playnite doesn't crash anymore, but the grid continues to show when custom integration is disabled. When there isn't data, the grid is collpased.

**Comment by Lacro59** [comment]
It's not possible to have a another tag element in wpf.

In addition, "Hltb Has DataLog" don't exist.
The good is "Hltb_HasData".

For the next release, I will add "Htlb_EnableIntegrationInCustomTheme" for indicate if the user has actived the custom theme integration.

**Comment by Lacro59** [comment]
Is the problem still present with the latest versions?

**Comment by eminaguil** [comment]
I have pause the changes around this. This weekend I will check the issue

**Comment by eminaguil** [comment]
> Is the problem still present with the latest versions?

No, the problem it's no more.
