### ISSUE TITLE
 the progress bar narrows

### ISSUE THREAD

**Issue by Lacro59** [Lacro59/playnite-howlongtobeat-plugin#53]
from Leon12345 on forum (https://playnite.link/forum/thread-309-post-2450.html#pid2450)

When it starts with playnite, it looks fine like this
![](https://i.imgur.com/4S82XO5.png)
but each time I select another game, the bar keeps getting smaller, and ends up looking like this
![](https://i.imgur.com/aFEXzQP.png)

**Comment by Vasily-Biryukov** [comment]
I have the same issue after plugin update.
I uninstall the plugin, remove all plugin data from %AppData%\playnite\ExtensionsData and install plugin again. This helps for me.
