### ISSUE TITLE
Display? Issues With Different Appearance Options

### ISSUE THREAD

**Issue by LeeThompson** [Lacro59/playnite-howlongtobeat-plugin#56]
This is a minor issue but perhaps major to some depending on theme and what's going on "behind the scenes".

This is hard to describe but for some games it's showing "2h 0m".

In this example, Beamdog's "Baldur's Gate" Enhanced Edition:

![HowToBeatIssue_1](https://user-images.githubusercontent.com/1982261/98724116-19a82700-2348-11eb-8615-b17516446e3c.png)

The plugin sees the correct record and times.

![HowToBeatIssue_2](https://user-images.githubusercontent.com/1982261/98724407-90ddbb00-2348-11eb-9bd9-2b2614ffd10a.png)

Now it just shows 2h 0m on the bar.

I've tried deleting the plugin data and re-downloading it but it makes no difference.

If I change the extension's view, like in this case, the theme integration, now it works 

![HowToBeatIssue_3](https://user-images.githubusercontent.com/1982261/98724307-6b50b180-2348-11eb-90c8-7200102d79a5.png)

**Comment by Lacro59** [comment]
Can you try again with [v1.1.1](https://github.com/Lacro59/playnite-howlongtobeat-plugin/releases/tag/v1.1.1)?

**Comment by LeeThompson** [comment]
Seems better in 1.1.1, will do more testing and reopen if there's issues.

**Comment by LeeThompson** [comment]
Still some issues, noticed Banner Saga 1-3 all showed the same times.  Deleted HowToBeat data and re-added it, the popup select times are correct but then the Playnite entry shows the times for the other games in the series.

**Comment by LeeThompson** [comment]
My next step is going to be the plugin level delete all data and try again, maybe something's messed up.

**Comment by BUglys** [comment]
Hi, a little more info on this (on my setup at least): 

On startup, correct display/times are shown. Selecting 2nd game shows correct time but the progress bar narrows in height to about 50%. Selecting 3rd game shows correct time but the progress bar narrows again. Selecting 4th game and the time becomes locked at whatever the 3rd game time was. Progress bar remains narrow.

This happens with Time displayed above and below, but interestingly the issue isn't present when time displayed 'Inside progress bar' is selected. 

LeeThomson's screenshots appear to be showing the bar at it's narrowest. As an aside, it looks pretty good narrow...

Hope this helps.
