### ISSUE TITLE
Feature Request: Show System Type

### ISSUE THREAD

**Issue by LeeThompson** [Lacro59/playnite-howlongtobeat-plugin#57]
I have some emulated games in my library as well as PC, it would be helpful when batch adding titles if the selection window would show the type (PC, Sega Genesis, Atari 2600 etc).   (Perhaps the source field as well.)

**Comment by Lacro59** [comment]
Can you give a example?

**Comment by LeeThompson** [comment]
Some examples:
* Atlantis / Atlantis II (Which existed for the Atari 2600 and, much later, unrelated adventure games on the PC)
* Choplifter  (https://en.wikipedia.org/wiki/Choplifter)
* Road Rash (Sega Genesis, later 3DO, Windows PC)

When the HowLongToBeat search window is up, it does not mention what platform it's looking it up for.

(Also when updating your library with HowLongToBeat there's no cancel queue option, just the title you're adding at the moment.)
