### ISSUE TITLE
HLTB Grid View Button Bug

### ISSUE THREAD

**Issue by TheRhysWyrill** [Lacro59/playnite-howlongtobeat-plugin#58]
So i've been going through my collection and noticed that when switching from details view to grid view, the HLTB button appears to multiple, it's currently up to 5 and it's only showing like this on the grid view details pane as shown below.
![2020-11-13 12_37_29-Playnite](https://user-images.githubusercontent.com/27123572/99073285-8a03b200-25ad-11eb-81c7-2a579fc22f8b.png)

It shows up as intended in detail view as you can see.
![2020-11-13 12_42_01-Playnite](https://user-images.githubusercontent.com/27123572/99073420-c6cfa900-25ad-11eb-8626-4118736322df.png)

Not entirely sure what is causing this nor if there's anything I can do to fix it.

**Comment by TheRhysWyrill** [comment]
Seems restarting Playnite removes the duplicate buttons but that's not really a fix, also doesn't matter what theme is being used, it seems to happen on every theme if you switch between detail and grid view.

**Comment by Lacro59** [comment]
A new release is published.
Can you test with it?
Thanks.

**Comment by TheRhysWyrill** [comment]
Just installed 1.2 of the extension and switching from Grid View to Details View and back again the button bug still persists unfortunately.

**Comment by Lacro59** [comment]
I found & resolved the issue for the next release.
