### ISSUE TITLE
Extension deletes all game tags when adding HLTB tag

### ISSUE THREAD

**Issue by darklinkpower** [Lacro59/playnite-howlongtobeat-plugin#59]
Steps to reproduce:
1. Add tags to any game
2. With the extension enabled, select a game to trigger HLTB data download of the game
3. Existing tags get wiped if data is found. Only HLTB remains in game tags.

**Comment by Lacro59** [comment]
A new release is published.
Can you test with it?
Thanks.

**Comment by darklinkpower** [comment]
For some reason automatic data download on selection is not working, but manually searching and selecting the game no longer deletes the existing tags in the new version.

**Comment by Lacro59** [comment]
For this plugin, the data is always downloaded manualy.
