### ISSUE TITLE
Add Tags misses some games

### ISSUE THREAD

**Issue by azuravian** [Lacro59/playnite-howlongtobeat-plugin#62]
I have gathered the HLTB data for all of my games.  I then used the "Add tag to all games" option.  I have a total of 39 games that have HLTB data, but do not get a tag added to them.

The games with missing tags are from multiple sources, including GOG, Steam, Humble, and manual entry.

The only entry in my log related to this is the following:
`07-01 20:11:52.382|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ProgressWindowFactory
07-01 20:12:33.134|INFO|PluginDatabaseObject`3:HowLongToBeat - AddTagAllGame() - 00:40.68 for 2125/2125 items
07-01 20:12:33.134|DEBUG|WindowFactory:Closing window Playnite.Windows.ProgressWindowFactory, True.`

**Comment by Lacro59** [comment]
Can you give me many game example?

**Comment by azuravian** [comment]
The first example is "Alwa's Legacy"
The image linked below contains a list of all 39 games that have this problem for me.

[https://i.imgur.com/jFTNwMd.png](url)

**Comment by azuravian** [comment]
I just found something when searching the first three.  They appear to all be games that have a HLTB time, but not one for just "Main Story".
