### ISSUE TITLE
Request - Allow option to disable tags

### ISSUE THREAD

**Issue by SlipperyJim** [Lacro59/playnite-howlongtobeat-plugin#76]
Hi Lacro59.

Would it be possible to add an option so that the tags do not get created every time Playnite starts please? I don't use them but I can't delete them as they are always re-created when I do and so I always have loads of unused tags cluttering up the ones I do use. I use the other functionality of the extension so wouldn't want to disable it.

Thanks very much.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-howlongtobeat-plugin/commit/15ae7b2b7accc40cb223291ccbd36ee4e16e8782
