### ISSUE TITLE
Add tag to games missing HLTB data

### ISSUE THREAD

**Issue by sharkusmanch** [Lacro59/playnite-howlongtobeat-plugin#80]
When adding HLTB data to my entire library, some games won't be able to be auto-matched as expected. In this case manual searching/matching is usually required.

It would be nice to have a tag or some sort of filtering mechanism to quickly see which games in my library do not have HLTB data so that I can fix the matching.

**Comment by Lacro59** [comment]
https://github.com/Lacro59/playnite-howlongtobeat-plugin/commit/0835a58e484c4e6a78061babc9eb09983c6316e3
