### ISSUE TITLE
Playnite will does not see this version

### ISSUE THREAD

**Issue by bmtphoenix** [Lacro59/playnite-howlongtobeat-plugin#82]
When I load Playnite, I get the following notification: HowLongToBeat Update Available v1.3 to v2.0. If I click, it sends me here - https://github.com/Lacro59/playnite-gameactivity-plugin/releases/tag/v2.0 - which is obviously not correct.

**Comment by Lacro59** [comment]
It will be fixed with the next release on Playnite 9.
