### ISSUE TITLE
How can I get rid of this text line? 

### ISSUE THREAD

**Issue by QubeRubix** [Lacro59/playnite-howlongtobeat-plugin#86]
No matter how I mess with the appearance settings I can not get this text Line to go away. Is it the theme I am using
![Capture](https://user-images.githubusercontent.com/90926297/133828284-6bd1a0bc-2ce3-4280-9ce3-f9108c8b7fe9.PNG)
![Capture3](https://user-images.githubusercontent.com/90926297/133828374-2407f177-a673-45f2-b60d-eb53b17b27b2.PNG)
?

**Comment by darklinkpower** [comment]
That line is from the theme files, not the extension. You need to modify the theme file (DetailsViewGameOverview.xaml) to remove it.

**Comment by QubeRubix** [comment]
Thank you! I was able to delete some script within that file to stop showing that line!
