### ISSUE TITLE
When selecting HLTB icon in sidebar or top panel Playnite is crashing

### ISSUE THREAD

**Issue by Jhanlon95** [Lacro59/playnite-howlongtobeat-plugin#89]
When I select the HLTB icon on the sidebar or on the top bar Playnite crashes 

![image](https://user-images.githubusercontent.com/11045596/135598490-a720e6d2-2942-4ee0-bb60-981b65225ad2.png)

[hltb crash.zip](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/7265923/hltb.crash.zip)

**Comment by Lacro59** [comment]
Can you try with the v2.1.1?

**Comment by Jhanlon95** [comment]
It still happens on both buttons. This is the crash log

[hltb crash 2-1-1.zip](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/7267113/hltb.crash.2-1-1.zip)

**Comment by Lacro59** [comment]
Can you go in plugin data folder and post your HltbUserStats.json?
![image](https://user-images.githubusercontent.com/124054/135622166-16e70452-fb96-430b-bdb8-eea8fd28231b.png)

**Comment by Jhanlon95** [comment]
Yep sure, this is the file here, I had to put it into a zip folder as GitHub didn't like that it was a json file

[HltbUserStats.zip](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/7267232/HltbUserStats.zip)

**Comment by Lacro59** [comment]
Can you try this version? Thanks.
[playnite-howlongtobeat-plugin_2_1_1.zip](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/7267712/playnite-howlongtobeat-plugin_2_1_1.zip)

**Comment by Jhanlon95** [comment]
Just tried it there and they no longer cause crashes when clicking on them

Selecting the sidebar button
![image](https://user-images.githubusercontent.com/11045596/135632495-da4c96c4-dda0-49db-9b31-dd1b800b8fc2.png)

Selecting the top panel button
![image](https://user-images.githubusercontent.com/11045596/135632544-b47fffd1-93d2-4aa9-b917-f2168041be0f.png)

**Comment by Lacro59** [comment]
Great!
