### ISSUE TITLE
Playnite crashes on HLTB authentication

### ISSUE THREAD

**Issue by tynansdtm** [Lacro59/playnite-howlongtobeat-plugin#97]
Playnite closes every time I enter my How Long to Beat account name and (correct) password. I briefly see my HLTB account page. Version 2.2, latest version of Playnite.

**Comment by Don-Dragon** [comment]
Hi there,

I am also getting this same issue as above, same as OP (version 2.2, latest public Playnite). I have attached excerpts of my playnite.log & extensions.log file in case it helps.


[debug_playnite.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/7382957/debug_playnite.log)
[debug_extensions.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/7382958/debug_extensions.log)

**Comment by tynansdtm** [comment]
[playnite.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/7383801/playnite.log)
[extensions.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/7383802/extensions.log)

These ones?
